/*
 * Generated on :codegenerator_date:
 */

package org.netbeans.rest.application.config;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 * @author Franky Laseure
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
//Custom code, do not change this line
//add here custom operations
//Custom code, do not change this line   
:repeattables:
        resources.add(:project:.restservices.RS:Table:.class);
        resources.add(:project:.restservices.RS:Table:_select.class);
        resources.add(:project:.restservices.RS:Table:_secureselect.class);
:repeattables:
:repeatviews:
        resources.add(:project:.restservices.RS:Table:.class);
        resources.add(:project:.restservices.RS:Table:_select.class);
        resources.add(:project:.restservices.RS:Table:_secureselect.class);
:repeatviews:
        return resources;
    }
}
//needs customization by programmer ?

